---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  kasm:
    hostname: "kasm"
    container_name: "kasm"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "'lscr.io/linuxserver/kasm:latest'"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    ports:
      - '3002:3000'
      - '4443:4443'
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/kasm:/opt:rw"
      - "${APPFOLDER}/kasm/profiles:/profiles:rw"
      - "unionfs:/mnt:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.kasm-rtr.entrypoints=https"
      - "traefik.http.routers.kasm-rtr.rule=Host(`kasm.${DOMAIN}`)"
      - "traefik.http.routers.kasm-rtr.tls=true"
      - "traefik.http.routers.kasm-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.kasm-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.kasm-rtr.service=kasm-svc"
      - "traefik.http.services.kasm-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.kasm-svc.loadbalancer.server.port=4443"
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
