---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  plex:
    hostname: "plex"
    container_name: "plex"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "PLEX_CLAIM=${PLEX_CLAIM_ID}"
      - "VERSION=${PLEXVERSION}"
      - "ADVERTISE_IP=http://plex.${DOMAIN}:443"
      - "DOCKER_MODS=ghcr.io/gilbn/theme.park:plex|ghcr.io/dockserver/docker-mod-healthcheck:latest"
      - "TP_THEME=${PLEXTHEME}"
      - "TP_ADDON=${PLEXADDON}"
      ##- "NVIDIA_VISIBLE_DEVICES=all"
      ##- "NVIDIA_DRIVER_CAPABILITIES=all"
    image: "lscr.io/linuxserver/plex:latest"
    restart: "${RESTARTAPP}"
    ##devices:
    ##   - "/dev/dri:/dev/dri"
    ##runtime: "nvidia"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/plex/database:/config:rw"
      - "${APPFOLDER}/plex/transcode:/transcode:rw"
      - "/dev/shm:/ram_transcode:rw"
      - "unionfs:/mnt:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex-rtr.tls=true"
      - "traefik.http.routers.plex-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.plex-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
